# Hydra Group Configuration for Models (Located in config/models/main.yaml)

architect_default:
  _target_: "builtins.dict" # Using dict as a placeholder if no specific class is needed
  temperature: ${default_model_settings.temperature}
  max_tokens: ${default_model_settings.max_tokens}
  primary: "qwen/qwen3-14b:free"
  fallback: "qwen/qwen3-8b:free"

maestro_default:
  _target_: "builtins.dict"
  temperature: ${default_model_settings.temperature}
  max_tokens: ${default_model_settings.max_tokens}
  primary: "qwen/qwen3-14b:free"
  fallback: "qwen/qwen3-8b:free"

objective_generator:
  _target_: "builtins.dict"
  temperature: ${default_model_settings.temperature}
  max_tokens: ${default_model_settings.max_tokens}
  primary: "qwen/qwen3-14b:free"
  fallback: "qwen/qwen3-8b:free"

capacitation_generator:
  _target_: "builtins.dict"
  temperature: ${default_model_settings.temperature}
  max_tokens: ${default_model_settings.max_tokens}
  primary: "qwen/qwen3-14b:free"
  fallback: "qwen/qwen3-8b:free"

error_analyzer:
  _target_: "builtins.dict"
  temperature: ${default_model_settings.temperature}
  max_tokens: ${default_model_settings.max_tokens}
  primary: "qwen/qwen3-14b:free"
  fallback: "qwen/qwen3-8b:free"
