# Technical Debt Configuration

default_severity_weights:
  CODE_SMELL: 1.0
  ARCHITECTURAL: 1.5
  PERFORMANCE: 1.3
  SECURITY: 2.0
  TEST_COVERAGE: 0.8
  DOCUMENTATION: 0.5
  DEPRECATED: 1.2

thresholds:
  file_loc: 300
  function_loc: 50
  cyclomatic_complexity: 10

scan_settings:
  include_dirs:
    - agent
    - tools
  exclude_dirs:
    - __pycache__
    - venv
    - .git

report_settings:
  output_dir: reports/
  format: markdown
  max_high_priority_items: 10

integration:
  memory_enabled: true
  jira_integration: false
  github_issues_integration: false