# Base configuration for Hephaestus
# This file is included by default.yaml

# Default memory file path
memory_file_path: "reports/memory/HEPHAESTUS_MEMORY.json"

# Default model temperature and max tokens
# These can be overridden in specific model configurations
default_model_settings:
  temperature: 0.3 # Default temperature from original default.yaml
  max_tokens: -1 # Default max_tokens from original default.yaml

# Model configurations will be loaded from model_config.yaml
# We define a placeholder here so Hydra knows about the 'models' group
models: {}

# Validation strategies will be loaded from validation_config.yaml
# We define a placeholder here so Hydra knows about the 'validation_strategies' group
validation_strategies: {}

# Code analysis thresholds from hephaestus_config.json
code_analysis_thresholds:
  file_loc: 300
  function_loc: 50
  function_cc: 10

# Other general settings can be added here
# For example, if 'example_config.json' had relevant general settings,
# they would be migrated here.
# Based on 'example_config.json':
# api_key: "your-api-key-here" # This should be managed via environment variables or secrets, not committed
# default_model: "gpt-3.5-turbo" # This is superseded by the detailed model configs
# base_url: "https://openrouter.ai/api/v1" # This could be part of LLM client config if needed
log_level: "INFO" # from example_config.json
max_retries: 5 # from example_config.json (aumentado de 3)
timeout_seconds: 60 # from example_config.json (aumentado de 30)

# Rate limiting configuration - Otimizado para múltiplos modelos
rate_limiting:
  enabled: true
  max_concurrent_llm_calls: 3  # Aumentado para aproveitar modelos diferentes
  calls_per_minute: 45  # Aumentado (15 por modelo em média)
  retry_delay_seconds: 5
  exponential_backoff: true

# Real-time evolution settings
real_time_evolution:
  enabled: true
  fitness_threshold: 0.1
  max_parallel_tests: 1
  mutation_interval: 60
  scan_interval: 60
  risk_threshold: 0.3

# Log and backup cleanup settings
log_cleaner:
  backup_retention_days: 7
  log_retention_days: 30
  max_backup_files: 50
  max_log_size_mb: 100
  auto_cleanup_interval_hours: 24
