# Default configuration for Hephaestus
# This is the main entry point for Hydra configuration.

defaults:
  - base_config            # Load base settings from base_config.yaml
  - models: main           # Load model configurations from config/models/main.yaml
  - validation_strategies: main # Load validation strategies from config/validation_strategies/main.yaml
  - _self_                  # Allows values in this file to override defaults from included files

# Code analysis thresholds used by agent.brain
code_analysis_thresholds:
  file_loc: 300
  function_loc: 50
  function_cc: 10

# You can override specific values here if needed, for example:
# memory_file_path: "MY_CUSTOM_MEMORY.json"

# Add a top-level key to confirm this file is loaded, if necessary for debugging
config_source: "default.yaml"

# Configurações dos modelos LLM - Distribuição inteligente para evitar rate limiting
# Cada agente usa um modelo diferente para maximizar throughput
models:
  # Architect - Precisa de raciocínio complexo e contexto longo
  architect_default: "deepseek/deepseek-r1-0528:free"
  
  # Maestro - Coordenação estratégica, precisa de boa compreensão
  maestro_default: "mistralai/mistral-small-3.2-24b-instruct:free"
  
  # Code Reviewer - Análise técnica precisa
  code_reviewer: "qwen/qwen3-14b:free"
  
  # Log Analyzer - Análise de padrões e logs
  log_analyzer_default: "qwen/qwen3-8b:free"
  
  # Sommelier - Avaliação de qualidade
  sommelier_default: "deepseek/deepseek-r1-0528-qwen3-8b:free"
  
  # Frontend Artisan - Criatividade e design
  frontend_artisan_default: "moonshotai/kimi-dev-72b:free"
  
  # Bug Hunter - Detecção precisa de problemas
  bug_hunter_default: "qwen/qwen3-32b:free"

# Configurações do Bug Hunter Agent
bug_hunter:
  scan_interval: 120  # segundos entre scans (aumentado para reduzir carga)
  max_concurrent_fixes: 1  # máximo de correções simultâneas
  auto_fix_enabled: true  # correção automática habilitada
  scan_syntax_errors: true
  scan_import_errors: true
  scan_log_errors: true
  scan_test_failures: true
  scan_performance_issues: true

# Configurações do Real-Time Evolution Engine - BALANCEADO PARA EXECUÇÃO + EVOLUÇÃO
real_time_evolution:
  enabled: true  # ✅ HABILITADO - LLM funcionando agora!
  mutation_interval: 600  # 10 minutos entre mutações (mais controlado)
  max_parallel_tests: 1  # máximo de testes simultâneos (controlado)
  fitness_threshold: 0.25  # limiar realista para deployment (25%+ de melhoria)
  risk_threshold: 0.35  # limiar moderado de risco (máx 35% de risco)
  evolution_cooldown: 300  # 5 minutos de cooldown entre ciclos evolutivos
  force_execution_mode: false  # permite evolução controlada
  execution_priority: true  # prioriza execução sobre evolução
  max_mutations_per_hour: 3  # limite controlado - 3 mutações por hora
  require_success_before_mutation: false  # permite mutação mesmo com falhas

# Configurações de Rate Limiting para API - OTIMIZADO PARA MÚLTIPLAS CHAVES
rate_limiting:
  enabled: true
  max_concurrent_llm_calls: 3  # aumentado - temos 5 chaves agora!
  calls_per_minute: 60  # aumentado - distribuição entre chaves
  retry_delay_seconds: 5  # reduzido - fallback automático é rápido
  exponential_backoff: true  # usar backoff exponencial
  use_multiple_keys: true  # usa sistema de múltiplas chaves
  key_rotation_enabled: true  # rotaciona entre chaves automaticamente

# Evolution Analytics Configuration - HABILITADO PARA MONITORAMENTO
evolution_analytics:
  retention_days: 14  # aumentado para melhor análise histórica
  analysis_interval_hours: 6  # análise mais frequente para detectar padrões
  min_data_points: 3  # reduzido para análise mais rápida
  chart_generation: true  # ✅ HABILITADO - útil para visualizar evolução
  prediction_enabled: true  # ✅ HABILITADO - predição de tendências
  auto_cleanup: true
  detailed_logging: true  # log detalhado para debug
  performance_tracking: true  # tracking de performance das mutações

# Configurações do Parallel Reality Testing - 3ª META-FUNCIONALIDADE
parallel_reality:
  enabled: true  # ✅ HABILITADO - Sistema de múltiplas estratégias paralelas
  max_parallel_tests: 3  # máximo de estratégias testadas simultaneamente
  early_termination_threshold: 0.2  # diferença mínima para terminar testes cedo
  winner_selection_interval: 30  # segundos entre verificações de vencedor
  min_execution_time: 10  # tempo mínimo de execução por teste
  max_session_time: 300  # 5 minutos máximo por sessão de teste
  strategy_types: ["conservative", "aggressive", "balanced", "experimental", "optimized"]
  learning_enabled: true  # aprende com comparações entre estratégias
  resource_monitoring: true  # monitora uso de recursos por estratégia
  historical_optimization: true  # usa dados históricos para otimizar estratégias

# Configurações do Meta-Learning Intelligence - 4ª META-FUNCIONALIDADE
meta_learning:
  enabled: true  # ✅ HABILITADO - Sistema que aprende como aprender melhor
  base_learning_rate: 0.1  # taxa base de aprendizado
  adaptive_rate_enabled: true  # ajusta taxa baseado no contexto
  pattern_detection_threshold: 5  # mínimo de eventos para detectar padrões
  memory_retention_threshold: 0.3  # limiar para reter memórias
  transfer_learning_enabled: true  # permite transferência entre domínios
  max_learning_events: 1000  # máximo de eventos na memória
  bias_detection_enabled: true  # detecta vieses no aprendizado
  continuous_optimization: true  # otimização contínua em background
  adaptive_memory_enabled: true  # sistema de memória que adapta retenção

# Configurações do Self-Awareness Core 2.0 - 5ª META-FUNCIONALIDADE
self_awareness:
  enabled: true  # ✅ HABILITADO - Sistema de consciência profunda do próprio estado cognitivo
  reflection_interval: 300  # 5 minutos entre auto-reflexões profundas
  state_monitoring_interval: 60  # 1 minuto entre snapshots de estado cognitivo
  bias_detection_enabled: true  # detecta vieses cognitivos próprios
  personality_evolution_enabled: true  # permite evolução da personalidade
  metacognitive_awareness: true  # consciência sobre próprios processos de pensamento
  continuous_monitoring: true  # monitoramento contínuo em background
  wellness_threshold: 0.4  # limiar de bem-estar para auto-otimização
  fatigue_detection_enabled: true  # detecta fadiga cognitiva
  max_state_history: 1000  # máximo de snapshots na memória
  self_optimization_triggers: true  # triggers automáticos de auto-otimização
  bias_correction_enabled: true  # correção automática de vieses detectados
  cognitive_load_monitoring: true  # monitora sobrecarga cognitiva
  decision_quality_tracking: true  # acompanha qualidade das decisões

# Configurações do Meta-Objective Generator - 6ª META-FUNCIONALIDADE
meta_objective_generator:
  enabled: true  # ✅ HABILITADO - Sistema que gera objetivos para melhorar objetivos
  generation_interval: 600  # 10 minutos entre gerações automáticas de meta-objetivos
  capability_analysis_interval: 1800  # 30 minutos entre análises de capacidade
  max_concurrent_objectives: 5  # máximo de meta-objetivos ativos simultaneamente
  pattern_detection_threshold: 3  # mínimo de eventos para detectar padrões
  improvement_threshold: 0.1  # limiar mínimo de melhoria (10%)
  quality_threshold: 0.7  # limiar de qualidade para objetivos gerados
  recursive_depth: 3  # profundidade máxima de recursão em meta-objetivos
  strategic_planning_enabled: true  # permite planejamento estratégico de longo prazo
  auto_capability_assessment: true  # avaliação automática de capacidades
  pattern_learning_enabled: true  # aprendizado de padrões de sucesso
  objective_evolution_enabled: true  # evolução contínua de objetivos
  context_awareness_level: "high"  # nível de consciência contextual (low/medium/high)
  creativity_boost_factor: 1.2  # fator de aumento de criatividade

# Configurações do Temporal Intelligence - 7ª META-FUNCIONALIDADE
temporal_intelligence:
  enabled: true  # ✅ HABILITADO - Sistema de consciência temporal completa
  analysis_interval: 1800  # 30 minutos entre análises temporais automáticas
  pattern_detection_threshold: 3  # mínimo de eventos para detectar padrões temporais
  prediction_horizon_days: 7  # horizonte de predição em dias
  max_historical_events: 10000  # máximo de eventos históricos em memória
  pattern_confidence_threshold: 0.6  # limiar de confiança para validar padrões (60%)
  temporal_memory_enabled: true  # sistema de memória temporal inteligente
  proactive_planning_enabled: true  # planejamento proativo baseado em predições
  historical_learning_enabled: true  # aprendizado contínuo de padrões históricos
  future_prediction_enabled: true  # predição de necessidades e oportunidades futuras
  cyclical_pattern_detection: true  # detecção de padrões cíclicos
  trend_analysis_enabled: true  # análise de tendências temporais
  correlation_analysis_enabled: true  # análise de correlações temporais entre eventos
  temporal_decision_making: true  # tomada de decisão considerando linha temporal completa
  predictive_optimization: true  # otimização baseada em predições futuras
  temporal_context_awareness: true  # consciência completa do contexto temporal

# Configurações do Dynamic Agent DNA System - 8ª META-FUNCIONALIDADE
dynamic_agent_dna:
  enabled: true  # ✅ HABILITADO - Sistema de evolução darwiniana para agentes
  population_size: 50  # tamanho máximo da população por tipo de agente
  mutation_rate: 0.1  # taxa de mutação genética (10%)
  selection_pressure: 0.3  # pressão de seleção natural (30% dos menos aptos eliminados)
  reproduction_rate: 0.2  # taxa de reprodução sexual (20% da população)
  generation_interval: 3600  # intervalo entre gerações em segundos (1 hora)
  fitness_threshold: 0.6  # limiar mínimo de fitness para sobrevivência
  genetic_diversity_target: 0.7  # objetivo de diversidade genética (70%)
  natural_selection_enabled: true  # seleção natural baseada em performance
  genetic_reproduction_enabled: true  # reprodução sexual entre agentes
  mutation_evolution_enabled: true  # evolução através de mutações
  speciation_enabled: true  # criação de novas espécies híbridas
  population_dynamics_enabled: true  # dinâmica populacional complexa
  darwinian_evolution_enabled: true  # evolução darwiniana completa
  cognitive_genetics_enabled: true  # genética cognitiva avançada
  fitness_based_selection: true  # seleção baseada em fitness real

# NOVA CONFIGURAÇÃO: Modo de Execução Forçada
execution_mode:
  enabled: true
  objective_priority: "high"  # prioridade máxima para objetivos
  evolution_cooldown_hours: 2  # 2 horas sem evolução
  max_objective_attempts: 3  # máximo 3 tentativas por objetivo
  objective_timeout_minutes: 30  # timeout de 30 minutos por objetivo
  force_simple_objectives: true  # força objetivos simples e executáveis
  skip_complex_refactoring: true  # pula refatorações complexas temporariamente
