# Default configuration for Hephaestus
# This is the main entry point for Hydra configuration.

defaults:
  - base_config            # Load base settings from base_config.yaml
  - models: main           # Load model configurations from config/models/main.yaml
  - validation_strategies: main # Load validation strategies from config/validation_strategies/main.yaml
  - _self_                  # Allows values in this file to override defaults from included files

# Code analysis thresholds used by agent.brain
code_analysis_thresholds:
  file_loc: 300
  function_loc: 50
  function_cc: 10

# You can override specific values here if needed, for example:
# memory_file_path: "MY_CUSTOM_MEMORY.json"

# Add a top-level key to confirm this file is loaded, if necessary for debugging
config_source: "default.yaml"

# Configurações dos modelos LLM - Distribuição inteligente para evitar rate limiting
# Cada agente usa um modelo diferente para maximizar throughput
models:
  # Architect - Precisa de raciocínio complexo e contexto longo
  architect_default: "deepseek/deepseek-r1-0528:free"
  
  # Maestro - Coordenação estratégica, precisa de boa compreensão
  maestro_default: "mistralai/mistral-small-3.2-24b-instruct:free"
  
  # Code Reviewer - Análise técnica precisa
  code_reviewer: "qwen/qwen3-14b:free"
  
  # Log Analyzer - Análise de padrões e logs
  log_analyzer_default: "qwen/qwen3-8b:free"
  
  # Sommelier - Avaliação de qualidade
  sommelier_default: "deepseek/deepseek-r1-0528-qwen3-8b:free"
  
  # Frontend Artisan - Criatividade e design
  frontend_artisan_default: "moonshotai/kimi-dev-72b:free"
  
  # Bug Hunter - Detecção precisa de problemas
  bug_hunter_default: "qwen/qwen3-32b:free"

# Configurações do Bug Hunter Agent
bug_hunter:
  scan_interval: 120  # segundos entre scans (aumentado para reduzir carga)
  max_concurrent_fixes: 1  # máximo de correções simultâneas
  auto_fix_enabled: true  # correção automática habilitada
  scan_syntax_errors: true
  scan_import_errors: true
  scan_log_errors: true
  scan_test_failures: true
  scan_performance_issues: true

# Configurações do Real-Time Evolution Engine - OTIMIZADO PARA EXECUÇÃO
real_time_evolution:
  enabled: false  # DESABILITADO temporariamente para focar em execução
  mutation_interval: 300  # 5 minutos entre mutações (aumentado drasticamente)
  max_parallel_tests: 1  # máximo de testes simultâneos
  fitness_threshold: 0.5  # limiar mais alto para deployment
  risk_threshold: 0.2  # limiar mais baixo de risco
  evolution_cooldown: 1800  # 30 minutos de cooldown entre ciclos evolutivos
  force_execution_mode: true  # força modo de execução em vez de evolução

# Configurações de Rate Limiting para API
rate_limiting:
  enabled: true
  max_concurrent_llm_calls: 2  # reduzido para estabilidade
  calls_per_minute: 30  # reduzido para evitar rate limiting
  retry_delay_seconds: 10  # delay maior entre retries
  exponential_backoff: true  # usar backoff exponencial

# Evolution Analytics Configuration
evolution_analytics:
  retention_days: 7  # reduzido para limpeza mais frequente
  analysis_interval_hours: 12  # análise menos frequente
  min_data_points: 5  # menos pontos para análise
  chart_generation: false  # desabilitado para reduzir carga
  prediction_enabled: false  # desabilitado temporariamente
  auto_cleanup: true

# NOVA CONFIGURAÇÃO: Modo de Execução Forçada
execution_mode:
  enabled: true
  objective_priority: "high"  # prioridade máxima para objetivos
  evolution_cooldown_hours: 2  # 2 horas sem evolução
  max_objective_attempts: 3  # máximo 3 tentativas por objetivo
  objective_timeout_minutes: 30  # timeout de 30 minutos por objetivo
  force_simple_objectives: true  # força objetivos simples e executáveis
  skip_complex_refactoring: true  # pula refatorações complexas temporariamente
