# Default configuration for Hephaestus
# This is the main entry point for Hydra configuration.

defaults:
  - base_config            # Load base settings from base_config.yaml
  - models: main           # Load model configurations from config/models/main.yaml
  - validation_strategies: main # Load validation strategies from config/validation_strategies/main.yaml
  - _self_                  # Allows values in this file to override defaults from included files

# Code analysis thresholds used by agent.brain
code_analysis_thresholds:
  file_loc: 300
  function_loc: 50
  function_cc: 10

# You can override specific values here if needed, for example:
# memory_file_path: "MY_CUSTOM_MEMORY.json"

# Add a top-level key to confirm this file is loaded, if necessary for debugging
config_source: "default.yaml"

# Configurações dos modelos LLM
models:
  architect_default: "deepseek/deepseek-chat-v3-0324:free"
  maestro_default: "deepseek/deepseek-chat-v3-0324:free"
  code_reviewer: "mistralai/mistral-7b-instruct:free"
  log_analyzer_default: "deepseek/deepseek-chat-v3-0324:free"
  sommelier_default: "deepseek/deepseek-chat-v3-0324:free"
  frontend_artisan_default: "deepseek/deepseek-chat-v3-0324:free"
  bug_hunter_default: "deepseek/deepseek-chat-v3-0324:free"

# Configurações do Bug Hunter Agent
bug_hunter:
  scan_interval: 30  # segundos entre scans
  max_concurrent_fixes: 3  # máximo de correções simultâneas
  auto_fix_enabled: true  # correção automática habilitada
  scan_syntax_errors: true
  scan_import_errors: true
  scan_log_errors: true
  scan_test_failures: true
  scan_performance_issues: true

# Configurações do Real-Time Evolution Engine
real_time_evolution:
  enabled: true  # evolução em tempo real habilitada
  mutation_interval: 30  # segundos entre gerações de mutação
  max_parallel_tests: 3  # máximo de testes simultâneos
  fitness_threshold: 0.1  # limiar mínimo de fitness para deployment
  risk_threshold: 0.3  # limiar máximo de risco para deployment
